// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbrDoc5PrmqB0Q8MP5IyVmu4aWieuV8AA',
    appId: '1:424869671661:web:97c1ab36e6d3552916d2e4',
    messagingSenderId: '424869671661',
    projectId: 'help-me-6646e',
    authDomain: 'help-me-6646e.firebaseapp.com',
    storageBucket: 'help-me-6646e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYKgSVtsvTeAEN8LPxOC7fsuXnhOcrRnY',
    appId: '1:424869671661:android:e7757cff5baeb3bc16d2e4',
    messagingSenderId: '424869671661',
    projectId: 'help-me-6646e',
    storageBucket: 'help-me-6646e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALkzoY9vCU3kIjN9XA2HqDdu7Zz2yqnKU',
    appId: '1:424869671661:ios:7de7015caaf8d1e616d2e4',
    messagingSenderId: '424869671661',
    projectId: 'help-me-6646e',
    storageBucket: 'help-me-6646e.appspot.com',
    iosBundleId: 'com.example.urgenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALkzoY9vCU3kIjN9XA2HqDdu7Zz2yqnKU',
    appId: '1:424869671661:ios:7de7015caaf8d1e616d2e4',
    messagingSenderId: '424869671661',
    projectId: 'help-me-6646e',
    storageBucket: 'help-me-6646e.appspot.com',
    iosBundleId: 'com.example.urgenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbrDoc5PrmqB0Q8MP5IyVmu4aWieuV8AA',
    appId: '1:424869671661:web:f333759f545d47ac16d2e4',
    messagingSenderId: '424869671661',
    projectId: 'help-me-6646e',
    authDomain: 'help-me-6646e.firebaseapp.com',
    storageBucket: 'help-me-6646e.appspot.com',
  );
}
